# Railway configuration for FastAPI deployment
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
ENVIRONMENT = "production"
DEBUG = "false"
CORS_ALLOW_ORIGIN = "*"
# PORT is automatically set by Railway - don't override it
DATABASE_URL = { generate = true }
REDIS_URL = { generate = true }
OLLAMA_BASE_URL = "http://localhost:11434"
