[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
WEBUI_SECRET_KEY = { generate = true }
CORS_ALLOW_ORIGIN = "*"
DATA_DIR = "/app/backend/data"
PORT = "8080"
